export const data = [
    {
        Name: "Lily",
        Patterntype: "K1R, P1R and Pom Pom at the edge",
        Sleevedesign: "Baggy sleeve",
        Size: "M",
        Fittype: "Slim fit",
        Fabric: "Stretchy",
        Color: "green and white",
        Type: "Handmade",
    },
    {
        Name: "Josephine",
        Patterntype: "K1R P1R",
        Neckline: "off the shoulder",
        Sleevelength: "18cm",
        Fullbodylength: "100cm",
        Fittype: "slim fit",
        Fabric: "highly stretchy",
    },
    {
        Name: "Ruby ",
        Patterntype: "k1p1",
        Neckline: "optional",
        Sleevelength: "24cm",
        Length: "66cm",
        Waist: "44cm but highly stretchy",
        Fittype: "slim fit",
        Fabric: "highly stretchy",
        Color: "Red",
        Type: "handmade",
    },
    {
        Name: "Peaches",
        Patterntype: "Seed stitch and k1P1",
        Sleevedesign: "Baggy sleeve with K1P1 pattern and wide scrubby sparkle at the edge of the sleeve",
        Size: "M & L",
        Fittype: "Slim fit",
        Fabric: "Stretchy",
        Color: "Orange and white",
        Type: "Handmade",
    },
    {},
    {}
]